// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisplayFormController from "./display_form_controller"
application.register("display-form", DisplayFormController)

import FavouriteController from "./favourite_controller"
application.register("favourite", FavouriteController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)


import TasksController from "./tasks_controller"
application.register("tasks", TasksController)

import SwitchTabsController from "./switch_tabs_controller"
application.register("switch-tabs", SwitchTabsController)
